### ISSUE TITLE
Any plans to update this to .NET Core 3.0 or 3.1 soon?

### ISSUE THREAD

**Issue by anthcool** [exceptionnotfound/BlazorToDoList#2]
Would love to see this updated to RTM soon.  Thanks for the great article and code sample though!  Been trying to figure this out myself.  Appreciate it!

**Comment by johnt84** [comment]
I can pick this one up Matthew.  Think I've upgraded it to latest version of .Net Core (3.1) and got the app working again 😄

**Comment by exceptionnotfound** [comment]
Sounds fantastic John, thank you!

**Comment by anthcool** [comment]
Thank you John!  Much appreciated!

**Comment by johnt84** [comment]
No problem Anthony
